### ISSUE TITLE
Application should be hidden from Taskbar

### ISSUE THREAD

**Issue by tito** [mjs7231/pkmeter#5]
Pkmeter create an icon in the window list, with the name "Untitled Window". I think it should be handled more like as a widget rather than a window / application to manage.

![selection_128](https://cloud.githubusercontent.com/assets/37904/15082517/6a97b9e4-13c8-11e6-85c3-cddbd5b67b7e.png)

(Yes pkmeter is the icon between vim and steam ^^)

**Comment by pkkid** [comment]
Thanks for this. I've been getting mixed results on my systems. Running on Gnome 3.18 I was seeing the issue like you. But on Gnome 3.20 I'm not. I'll have to dig around in the QT5 settings a bit more to see what I'm doing wrong. 

I'm out of town for the weekend but plan to get to these issues next week.

**Comment by pkkid** [comment]
I'm still wondering if this is a gnome 3.18 bug that was fixed in 3.20. I am using the window hist Qt.Tool as mentioned in [this StackOverflow thread](http://stackoverflow.com/questions/4044994/hide-pyqt-app-from-taskbar), and it works on my home system running Gnome 3.20, but not on my work system running Gnome 3.18.

**Comment by pkkid** [comment]
This fixes it on my work machine.

commit 9c72358dc916c341a1bc2517c1d86f8a222eb740
Author: Michael Shepanski mjs7231@gmail.com
Date:   Thu May 12 21:33:06 2016 -0400
Fix application icon showing; Temp fix for broken plexserver display.
